### ISSUE TITLE
Updating ClearML Task after stopped faults build

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/machine.py#56] opened 2023-11-07 13:41 UTC
Spin off of https://github.com/sillsdev/machine/issues/130.

**Comment by johnml1135** [comment] 2023-11-07 14:15
The error that needs to be addressed is:
```
\x1b[41m\x1b[30mfail\x1b[39m\x1b[22m\x1b[49m: SIL.Machine.AspNetCore.Services.ClearMLMonitorService[0]
      Build faulted (6545d4793627520aa516b7eb). Error: ValueError : Task object can only be updated if created or in_progress [status=stopped fields=['hyperparams']]
```

**Comment by ddaspit** [comment] 2023-11-07 15:36
It looks like the ClearML task is being accessed after it was closed.

**Comment by mshannon-sil** [comment] 2023-11-07 19:06
Seems what might be happening is that it throws a `CanceledError` when the clearml task is stopped, and the except block tries to mark the task as failed when it is already stopped. In the except block, we should skip marking the task as failed if the error type is `CanceledError`. I'll go ahead and add this. I'm also going to remove the `stopping` status (see [issue #26](https://github.com/sillsdev/machine.py/issues/26)), and we can check to make sure cancellation works as intended.

**Comment by mshannon-sil** [comment] 2023-11-07 19:19
@johnml1135 or @Enkidu93 What jobs were you running that caused this error? I'd like to run them again with the changes.

**Comment by Enkidu93** [comment] 2023-11-07 20:01
> @johnml1135 or @Enkidu93 What jobs were you running that caused this error? I'd like to run them again with the changes.

I got this info second-hand, so I'm not sure, no. @johnml1135 might have more to go off of.

**Comment by mshannon-sil** [comment] 2023-11-08 19:52
Actually, it looks like marking the task as failed works even after the task has been stopped. So not all instances of accessing the task after it's been stopped are problematic. I'll look through other places in the code where the task is updated and see what I find.

**Comment by johnml1135** [comment] 2023-11-08 19:56
Did you try right after or did you wait for at least 5-10 seconds first?  It may be possible that a task marked "stopped" is not really stopped until everything resolves.  Also, don't be afraid to ask the ClearML Slack channel- I have had quite a few productive conversations there.

**Comment by ddaspit** [comment] 2023-11-08 20:04
It could be the calls to log metrics in the `ClearMLCallback` class in Huggingface.

**Comment by mshannon-sil** [comment] 2023-11-08 21:03
@johnml1135 I tried it both right after and about 30 seconds after it was marked as stopped, and marking the task as failed worked in both instances. Thanks for the reminder about the ClearML Slack channel. If I don't find the cause of the issue shortly, I'll ask there. This is a little difficult to debug without access to the stacktrace from machine.py.

@ddaspit That could be it. In the _ProgressCallback class, the `on_train_begin` and `on_step_end` functions update the task's progress first and afterward check if the task is cancelled. Moving the check to the beginning of those functions rather than the end might fix the problem.

**Closed** 2023-11-09 22:16 UTC
Labels: bug
